Считайте датасет из файла train.csv (это данные о выживаемости на Титанике) - 1 балл

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Выведите основную информацию о датасете: информацию о типах данных, число пропусков, средние значения и т.д. - 1 балл

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Посчитайте процент выживаемости у каждого класса пассажиров (Pclass) - 1 балл

In [ ]:
survival = df.groupby("Pclass")["Survived"].mean()*100
survival.round(2)

Pclass
1    62.96
2    47.28
3    24.24
Name: Survived, dtype: float64

Выведите самое популярное мужское и самое популярное женское имя на корабле - 1 балл

In [ ]:
def firstname(name):
    if '(' in name:
        start = name.find('(') + 1
        end = name.find(')')
        return name[start:end].split()[0]
    else:
        return name.split('.')[1].strip().split()[0]

df["FirstName"] = df["Name"].apply(firstname)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FirstName
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Owen
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Florence
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Lily
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,William

In [ ]:
male_names = df[df["Sex"] == "male"]["FirstName"].value_counts().idxmax()
female_names = df[df["Sex"] == "female"]["FirstName"].value_counts().idxmax()

In [ ]:
male_names

'William'

In [ ]:
female_names

'Anna'

Выведите самое популярное мужское и самое популярное женское имя на корабле в каждом классе - 2 балла

In [ ]:
def findname(group):
    return group.value_counts().idxmax()

nameclass = (
    df.groupby(['Pclass', 'Sex'])['FirstName']
    .apply(findname)
)
nameclass

Pclass  Sex
1       female    Elizabeth
        male        William
2       female    Elizabeth
        male        William
3       female         Anna
        male        William
Name: FirstName, dtype: object

Выведите часть таблицы с пассажирами, возраст которых больше 44 лет - 1 балл

In [ ]:
over44 = df[df["Age"] > 44][["Name", "Age", "Sex"]]
over44.head(10)

                                        Name   Age     Sex
6                    McCarthy, Mr. Timothy J  54.0    male
11                  Bonnell, Miss. Elizabeth  58.0  female
15          Hewlett, Mrs. (Mary D Kingcome)   55.0  female
33                     Wheadon, Mr. Edward H  66.0    male
52  Harper, Mrs. Henry Sleeper (Myna Haxtun)  49.0  female
54            Ostby, Mr. Engelhart Cornelius  65.0    male
62               Harris, Mr. Henry Birkhardt  45.0    male
92               Chaffee, Mr. Herbert Fuller  46.0    male
94                         Coxon, Mr. Daniel  59.0    male
96                 Goldschmidt, Mr. George B  71.0    male

Выведите часть таблицы с пассажирами, возраст которых меньше 44 лет и которые мужского пола - 2 балла

In [ ]:
men44 = df[(df["Age"] < 44) & (df["Sex"] == "male")][["Name", "Age", "Sex"]]
men44.head(10)

                              Name   Age   Sex
0          Braund, Mr. Owen Harris  22.0  male
4         Allen, Mr. William Henry  35.0  male
7   Palsson, Master. Gosta Leonard   2.0  male
12  Saundercock, Mr. William Henry  20.0  male
13     Andersson, Mr. Anders Johan  39.0  male
16            Rice, Master. Eugene   2.0  male
20            Fynney, Mr. Joseph J  35.0  male
21           Beesley, Mr. Lawrence  34.0  male
23    Sloper, Mr. William Thompson  28.0  male
27  Fortune, Mr. Charles Alexander  19.0  male

Выведите количества n-местных кабин (в которых было 2, 3, 4, ... человека) - 1 балл

In [ ]:
df = df[df['Cabin'].notna()]
cabins = df['Cabin'].str.split().explode()
cabin_counts = cabins.value_counts()
result = cabin_counts.value_counts().sort_index()
for key, val in result.items():
    if key >= 2:
        print(f"{key}-местных кабин: {val}")

2-местных кабин: 44
3-местных кабин: 6
4-местных кабин: 7